/**
 * This file was auto generated by Quark. 
 *
 * ANY MODIFICATIONS TO THIS FILE WILL BE LOST UPON RECONFIGURATION.
 *
 * If you want to change the contents of this file, edit the arguments 
 * passed to quark_add_shaders in your build script.
 */

#pragma once
#include "Quark/Utility/ShaderBinaryStructs.hpp"
	
struct SandboxVertexShaders {
	static const Quark::Photon::VertexShaderBinary shader;
};

struct SandboxFragmentShaders {
	static const Quark::Photon::FragmentShaderBinary shader;
};